apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    env  : stage
    app  : main
    tier : frontend
    owner: skozakov

spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name : wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
